name: "打卡"

#定时触发（北京时间 07:00、08:00、17:00、18:00）
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'  # 北京时间 07:00（UTC+0）
    - cron: '0 0 * * *'   # 北京时间 08:00（UTC+0）
    - cron: '0 9 * * *'   # 北京时间 17:00（UTC+0）
    - cron: '0 10 * * *'  # 北京时间 18:00（UTC+0）

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          check-latest: true

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sign in script
        env:
          USER: ${{ secrets.USER }}
          TZ: Asia/Shanghai
        run: |
          python main.py
